//
// Created by nicco on 30/11/2022.
//

#ifndef PLATFORMGAME_SPRITETYPE_H
#define PLATFORMGAME_SPRITETYPE_H

enum spriteType {IDLELEFT,IDLERIGHT, MOVERIGHT, MOVELEFT, JUMPRIGHT, JUMPLEFT,ATTACKRIGHT,ATTACKLEFT};

#endif //PLATFORMGAME_SPRITETYPE_H
